version: '2'
services:
  jhipsterspringcompilation-app:
    image: jhipsterspringcompilation
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterspringcompilation-mysql:3306/jhipsterspringcompilation?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipsterspringcompilation-mysql:
    extends:
      file: mysql.yml
      service: jhipsterspringcompilation-mysql
